### ISSUE TITLE
Library crash with version 23.03

### ISSUE THREAD

**Issue by jlesage** [MediaArea/MediaInfoLib#1730]
The library seems to crash when analyzing a file.  This crash is new to 23.03 and does not occur with version 22.12.

I first seen the crash when the library is used with FileBot.  I also reproduced the same crash by using the MediaInfo GUI.

I'm compiling from sources:
  - MediaInfo 23.03
  - MediaInfoLib 23.03
  - ZenLib 0.4.40
  - Debug enabled
  - Compiled with Clang
  - On Alpine Linux

Here is the backtrace from the core dump:

```
Core was generated by `/usr/bin/mediainfo-gui'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fca5141fb31 in ZenLib::BitStream_LE::Get (this=0x7fca43f1c8b0, HowMany=58719296) at ../../../../ZenLib/Source/ZenLib/BitStream_LE.h:57
57	../../../../ZenLib/Source/ZenLib/BitStream_LE.h: No such file or directory.
[Current thread is 1 (LWP 611)]
(gdb) bt
#0  0x00007fca5141fb31 in ZenLib::BitStream_LE::Get (this=0x7fca43f1c8b0, HowMany=58719296) at ../../../../ZenLib/Source/ZenLib/BitStream_LE.h:57
#1  0x00007fca5141fd1e in ZenLib::BitStream_LE::Skip (this=0x7fca43f1c8b0, bits=58719296) at ../../../../ZenLib/Source/ZenLib/BitStream_LE.h:95
#2  0x00007fca51416df6 in MediaInfoLib::File__Analyze::Trusted_IsNot (this=0x7fca4c948b00, Reason=0x7fca51bc0654 "Size is wrong") at ../../../Source/MediaInfo/File__Analyze.cpp:2926
#3  0x00007fca5142fcda in MediaInfoLib::File__Analyze::Get_EB (this=0x7fca4c948b00, Info=@0x7ffffbcfb890: 0, Name=0x7fca51c65a98 "Size") at ../../../Source/MediaInfo/File__Analyze_Buffer.cpp:1038
#4  0x00007fca51831f20 in MediaInfoLib::File_Mk::Header_Parse (this=0x7fca4c948b00) at ../../../Source/MediaInfo/Multiple/File_Mk.cpp:1527
#5  0x00007fca5141404d in MediaInfoLib::File__Analyze::Header_Manage (this=0x7fca4c948b00) at ../../../Source/MediaInfo/File__Analyze.cpp:2253
#6  0x00007fca51411c7d in MediaInfoLib::File__Analyze::Buffer_Parse (this=0x7fca4c948b00) at ../../../Source/MediaInfo/File__Analyze.cpp:1550
#7  0x00007fca5140f4af in MediaInfoLib::File__Analyze::Open_Buffer_Continue_Loop (this=0x7fca4c948b00) at ../../../Source/MediaInfo/File__Analyze.cpp:1121
#8  0x00007fca5140d8b6 in MediaInfoLib::File__Analyze::Open_Buffer_Continue (this=0x7fca4c948b00,
    ToAdd=0x7fca434a0210 "}\306r)g\224?\276m\225\333Fn\212\275\017\222\301\221\273)\226a\240\262L\344\254\345\002\327\305\375\202\247\212@(\243\266\370\005\210\031\377;\342\061~\016\354{\bޏd\371\003\336X\226\030\312M\335\027\024\006[{\200U\266\344\247\351x\243}\025\224\317C4\316\006\213w\235M8=P\276zb\023\232\244g\350\360\325U\021\300\300\304\326\020\340\062\026\365\234\225\306\vr\241\253k\001W\260J<\322\323\355\313\\c\235\342\036\244Q0\261y\035\311\325\026\262\315\343\r\177i\223\004\203\017\b\251\310Ko\272\351\221ͫ\275\063\210\230\212oJ\304\004\207\062\337\037-\375\332\061\361˹\264\371X\240\370\224\n[\030\205\016\370\361\060P"..., ToAdd_Size=142193) at ../../../Source/MediaInfo/File__Analyze.cpp:724
#9  0x00007fca51521e93 in MediaInfoLib::MediaInfo_Internal::Open_Buffer_Continue (this=0x7fca4c7f6cf0,
    ToAdd=0x7fca434a0210 "}\306r)g\224?\276m\225\333Fn\212\275\017\222\301\221\273)\226a\240\262L\344\254\345\002\327\305\375\202\247\212@(\243\266\370\005\210\031\377;\342\061~\016\354{\bޏd\371\003\336X\226\030\312M\335\027\024\006[{\200U\266\344\247\351x\243}\025\224\317C4\316\006\213w\235M8=P\276zb\023\232\244g\350\360\325U\021\300\300\304\326\020\340\062\026\365\234\225\306\vr\241\253k\001W\260J<\322\323\355\313\\c\235\342\036\244Q0\261y\035\311\325\026\262\315\343\r\177i\223\004\203\017\b\251\310Ko\272\351\221ͫ\275\063\210\230\212oJ\304\004\207\062\337\037-\375\332\061\361˹\264\371X\240\370\224\n[\030\205\016\370\361\060P"..., ToAdd_Size=142193) at ../../../Source/MediaInfo/MediaInfo_Internal.cpp:1677
#10 0x00007fca51a94ef2 in MediaInfoLib::Reader_File::Format_Test_PerParser_Continue (this=0x7fca4c7ae010, MI=0x7fca4c7f6cf0) at ../../../Source/MediaInfo/Reader/Reader_File.cpp:766
#11 0x00007fca51a92f4c in MediaInfoLib::Reader_File::Format_Test_PerParser (this=0x7fca4c7ae010, MI=0x7fca4c7f6cf0, File_Name=...) at ../../../Source/MediaInfo/Reader/Reader_File.cpp:313
#12 0x00007fca51a9263e in MediaInfoLib::Reader_File::Format_Test (this=0x7fca4c7ae010, MI=0x7fca4c7f6cf0, File_Name=<incomplete type>) at ../../../Source/MediaInfo/Reader/Reader_File.cpp:225
#13 0x00007fca5151ce88 in MediaInfoLib::MediaInfo_Internal::Entry (this=0x7fca4c7f6cf0) at ../../../Source/MediaInfo/MediaInfo_Internal.cpp:1372
#14 0x00007fca51516446 in MediaInfoLib::MediaInfo_Internal::Open (this=0x7fca4c7f6cf0, File_Name_=...) at ../../../Source/MediaInfo/MediaInfo_Internal.cpp:1128
#15 0x00007fca51531403 in MediaInfoLib::MediaInfoList_Internal::Entry (this=0x7fca4c868670) at ../../../Source/MediaInfo/MediaInfoList_Internal.cpp:212
#16 0x00007fca51530daa in MediaInfoLib::MediaInfoList_Internal::Open (this=0x7fca4c868670, File_Name=..., Options=MediaInfoLib::FileOption_Nothing) at ../../../Source/MediaInfo/MediaInfoList_Internal.cpp:148
#17 0x00007fca5152f998 in MediaInfoLib::MediaInfoList::Open (this=0x7fca4c83dee0, File=..., Options=MediaInfoLib::FileOption_Nothing) at ../../../Source/MediaInfo/MediaInfoList.cpp:118
#18 0x000055e0b26b849e in MainWindow::openFiles(QStringList) ()
#19 0x000055e0b26be349 in MainWindow::on_actionOpen_triggered() ()
#20 0x000055e0b26de02b in MainWindow::qt_metacall(QMetaObject::Call, int, void**) ()
#21 0x00007fca4fdb3c65 in ?? () from /usr/lib/libQt5Core.so.5
#22 0x00007fca50a9d784 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007fca50a9f537 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007fca50b45635 in ?? () from /usr/lib/libQt5Widgets.so.5
#25 0x00007fca50b45734 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#26 0x00007fca50bef534 in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#27 0x00007fca50ad10d2 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007fca50aa3295 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#29 0x00007fca50aa7bbf in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#30 0x00007fca4fd7d9aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#31 0x00007fca50aa717c in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#32 0x00007fca50ae12e4 in ?? () from /usr/lib/libQt5Widgets.so.5
#33 0x00007fca50ae262b in ?? () from /usr/lib/libQt5Widgets.so.5
#34 0x00007fca50aa3295 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#35 0x00007fca4fd7d9aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#36 0x00007fca50367cf8 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#37 0x00007fca5033cbbc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#38 0x00007fca4cbdbe06 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#39 0x00007fca4ede500b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#40 0x00007fca4ede526e in ?? () from /usr/lib/libglib-2.0.so.0
#41 0x00007fca4ede5320 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#42 0x00007fca4fdd5054 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#43 0x00007fca4fd7bd1b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#44 0x00007fca4fd84480 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#45 0x000055e0b26b3541 in main ()
```

Is there anything else I can provide to help investigate this issue ?

**Comment by JeromeMartinez** [comment]
@jlesage please test with ZenLib 0.4.41 just released.
As the issue may be in the include file, it is not only about binaries, MediaInfoLib compilation must use ZenLib 0.4.41.

If error is still there, we need the file, please share it (here or by email info@mediaarea.net)

**Comment by jlesage** [comment]
Thanks for your answer.  I don't see ZenLib 0.4.41 here: https://github.com/MediaArea/ZenLib/releases.  I guess you are in the process of creating a new release ?

**Comment by JeromeMartinez** [comment]
It will be on GH soon, in the meantime it is already at https://mediaarea.net/MediaInfo/Download

**Comment by g-maxime** [comment]
Tag created https://github.com/MediaArea/ZenLib/releases/tag/v0.4.41
