### ISSUE TITLE
Crash on mp3 under Clang AddressSanitizer

### ISSUE THREAD

**Issue by maxpozdeev** [MediaArea/MediaInfoLib#2054]
When I run my app using latest MI library with Address Sanitizer enabled in Xcode I have a crash with following message:
```
ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00012df51a11 at pc 0x0001027f7234 bp 0x00016e3b0a00 sp 0x00016e3b01b8
READ of size 20 at 0x00012df51a11 thread T13
...
0x00012df51a11 is located 1041 bytes to the right of 32-byte region [0x00012df515e0,0x00012df51600)
freed by thread T0 here:...

callstack:
    #0 0x1027f7230 in wrap_memcpy+0x138 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x17230)
    #1 0x1047d576c in MediaInfoLib::File__Analyze::Open_Buffer_Continue(unsigned char const*, unsigned long)+0xb04 (libmediainfo.dylib:arm64+0x576c)
    #2 0x1047d7040 in MediaInfoLib::File__Analyze::Open_Buffer_Continue(MediaInfoLib::File__Analyze*, unsigned char const*, unsigned long, bool, double)+0x964 (libmediainfo.dylib:arm64+0x7040)
    #3 0x104bfac94 in MediaInfoLib::File__Tags_Helper::Synched_Test()+0x240 (libmediainfo.dylib:arm64+0x42ac94)
    #4 0x104bfa99c in MediaInfoLib::File__Tags_Helper::Synchronize(bool&, unsigned long)+0x6c (libmediainfo.dylib:arm64+0x42a99c)
    #5 0x104963858 in MediaInfoLib::File_Mpega::Synchronize()+0x34 (libmediainfo.dylib:arm64+0x193858)
    #6 0x1047d8938 in MediaInfoLib::File__Analyze::Synchro_Manage()+0x70 (libmediainfo.dylib:arm64+0x8938)
    #7 0x1047d748c in MediaInfoLib::File__Analyze::Buffer_Parse()+0xf0 (libmediainfo.dylib:arm64+0x748c)
    #8 0x1047d5d7c in MediaInfoLib::File__Analyze::Open_Buffer_Continue_Loop()+0x108 (libmediainfo.dylib:arm64+0x5d7c)
    #9 0x1047d51a8 in MediaInfoLib::File__Analyze::Open_Buffer_Continue(unsigned char const*, unsigned long)+0x540 (libmediainfo.dylib:arm64+0x51a8)
    #10 0x104885d68 in MediaInfoLib::MediaInfo_Internal::Open_Buffer_Continue(unsigned char const*, unsigned long)+0x110 (libmediainfo.dylib:arm64+0xb5d68)
    #11 0x104bfa208 in MediaInfoLib::Reader_File::Format_Test_PerParser_Continue(MediaInfoLib::MediaInfo_Internal*)+0xbf8 (libmediainfo.dylib:arm64+0x42a208)
    #12 0x104bf949c in MediaInfoLib::Reader_File::Format_Test_PerParser(MediaInfoLib::MediaInfo_Internal*, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>> const&)+0x450 (libmediainfo.dylib:arm64+0x42949c)
    #13 0x104bf8e80 in MediaInfoLib::Reader_File::Format_Test(MediaInfoLib::MediaInfo_Internal*, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>>)+0x498 (libmediainfo.dylib:arm64+0x428e80)
    #14 0x104881db0 in MediaInfoLib::MediaInfo_Internal::Entry()+0x4aa4 (libmediainfo.dylib:arm64+0xb1db0)
    #15 0x10487d028 in MediaInfoLib::MediaInfo_Internal::Open(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>> const&)+0x1f4 (libmediainfo.dylib:arm64+0xad028)
    #16 0x104c970f0 in MediaInfo_Open+0xac (libmediainfo.dylib:arm64+0x4c70f0)
...
```

Error is occurred on attached mp3 file.  
[030.zip](https://github.com/MediaArea/MediaInfoLib/files/15448537/030.zip)

Possible patch included.  
[id3.patch](https://github.com/MediaArea/MediaInfoLib/files/15448496/id3.patch)

EDIT: wrong file uploaded previously

**Comment by maxpozdeev** [comment]
Error happens after #1896
